# Copyright (c) Tile-AI Corporation.
# Licensed under the MIT License.
"""Compile-only checks for the TPUv7/PPL descriptor boundary.

These tests stop at source generation.  They do not load a CModel or dispatch
work to the PCIe device.
"""

import pytest

import tilelang
from tilelang import tvm
import tilelang.language as T
from tilelang.engine.phase import LowerAndLegalize, OptimizeForTarget


def _target(programming_model="tpukernel"):
    chip = "sg2260e" if programming_model == "rv" else "bm1690"
    return f"tpu -mcpu={chip} -tpu-programming-model={programming_model}"


def _make_local_copy(scope, width=32):

    @T.prim_func
    def local_copy(
            source: T.Tensor((1, width), "float32"),
            destination: T.Tensor((1, width), "float32")):
        T.func_attr({"global_symbol": "local_copy", "tir.noalias": T.bool(True)})
        with T.Kernel(1, 1, is_cpu=True) as (_bx, _by):
            tile = T.alloc_shared((1, width), "float32", scope=scope)
            T.ppl_copy(source, tile)
            T.ppl_copy(tile, destination)

    return local_copy


def _make_raw_fill(scope, width):

    @T.prim_func
    def raw_fill():
        T.func_attr({"global_symbol": "raw_fill"})
        with T.Kernel(1, 1, is_cpu=True) as (_bx, _by):
            tile = T.alloc_shared((1, width), "float32", scope=scope)
            T.evaluate(T.call_extern(
                "handle", "tl.tpu.fill", tile.access_ptr("w"), T.float32(0)))

    return raw_fill


def _make_global_copy(width):

    @T.prim_func
    def global_copy(
            source: T.Tensor((width,), "uint8"),
            destination: T.Tensor((width,), "uint8")):
        T.func_attr({"global_symbol": "global_copy", "tir.noalias": T.bool(True)})
        with T.Kernel(1, 1, is_cpu=True) as (_bx, _by):
            T.ppl_copy(source, destination)

    return global_copy


def _make_exp_family_with_large_hw(op_name):

    @T.prim_func
    def exp_family():
        T.func_attr({"global_symbol": "exp_family"})
        with T.Kernel(1, 1, is_cpu=True) as (_bx, _by):
            # Each component is representable by dim4, while h*w is one past
            # the additional tpu_bdc_fp_exp limit.
            out = T.alloc_shared((1, 1, 256, 256), "float16")
            source = T.alloc_shared((1, 1, 256, 256), "float16")
            work0 = T.alloc_shared((1, 1, 256, 256), "float16")
            work1 = T.alloc_shared((1, 1, 256, 256), "float16")
            coeff = T.alloc_shared((64, 32), "float16")
            if op_name == "tl.tpukernel.exp":
                T.evaluate(T.call_extern(
                    "handle", op_name, out.access_ptr("rw"),
                    work0.access_ptr("rw"), work1.access_ptr("rw"),
                    coeff.access_ptr("rw")))
            else:
                T.evaluate(T.call_extern(
                    "handle", op_name, out.access_ptr("rw"),
                    source.access_ptr("r"), work0.access_ptr("rw"),
                    work1.access_ptr("rw"),
                    coeff.access_ptr("rw")))

    return exp_family


def _emit_source_without_address_assignment(function):
    """Reach source codegen with synthetic addresses for a static guard test.

    Four 256x256 FP16 scratch tiles intentionally exceed physical LMEM.  The
    test is about the independent PPL exp descriptor rule, so it skips the
    allocator and gives every lowered Allocate a harmless compile-only address.
    Nothing generated by this helper is compiled, loaded, or dispatched.
    """
    target = tvm.target.Target(_target())
    global_symbol = str(function.attrs["global_symbol"])
    module = tvm.IRModule({global_symbol: function})
    module = LowerAndLegalize(module, target)
    module = OptimizeForTarget(module, target)

    for global_var, lowered in list(module.functions.items()):
        allocation_names = []

        def collect(node):
            if isinstance(node, tvm.tir.Allocate):
                allocation_names.append(node.buffer_var.name)

        tvm.tir.stmt_functor.post_order_visit(lowered.body, collect)
        for index, name in enumerate(allocation_names):
            lowered = lowered.with_attr(
                name, tvm.tir.IntImm("int64", index * 64))
        module.update_func(global_var, lowered)

    codegen = tvm._ffi.get_global_func("target.build.tilelang_tpu")
    return codegen(module, target)


@pytest.mark.parametrize(
    "scope", ("shared", "shared.dyn", "local", "local.fragment"))
@pytest.mark.parametrize("programming_model", ("tpukernel", "rv"))
def test_all_normalized_local_scopes_reach_the_descriptor_copy_path(
        scope, programming_model):
    source = tilelang.lower(
        _make_local_copy(scope),
        target=_target(programming_model),
        runtime_mode="cmodel",
    ).kernel_source

    assert "__tilelang_tpu_tensor_info tile" in source
    expected = "rvt_dma_ld(" if programming_model == "rv" else "tpu_gdma_cpy_S2L("
    assert expected in source


def test_non_descriptor_allocation_scope_fails_closed():
    with pytest.raises(tvm.error.TVMError, match="unsupported scope local.var"):
        tilelang.lower(
            _make_raw_fill("local.var", 32),
            target=_target(),
            runtime_mode="cmodel",
        )


def test_descriptor_dimension_limit_accepts_65535_and_rejects_65536():
    source = tilelang.lower(
        _make_global_copy(65535),
        target=_target(),
        runtime_mode="cmodel",
    ).kernel_source
    assert ".shape = {1, 1, 1, 65535}" in source

    with pytest.raises(
            tvm.error.TVMError, match="dimension 65536.*dim4 limit 65535"):
        tilelang.lower(
            _make_global_copy(65536),
            target=_target(),
            runtime_mode="cmodel",
        )

    with pytest.raises(
            tvm.error.TVMError, match="dimension 65536.*dim4 limit 65535"):
        tilelang.lower(
            _make_raw_fill("shared.dyn", 65536),
            target=_target(),
            runtime_mode="cmodel",
        )

    with pytest.raises(tvm.error.TVMError, match="expects a positive dimension"):
        tilelang.lower(
            _make_raw_fill("shared.dyn", 0),
            target=_target(),
            runtime_mode="cmodel",
        )


@pytest.mark.parametrize(
    "op_name", ("tl.tpukernel.exp", "tl.tpukernel.sigmoid"))
def test_exp_family_rejects_h_w_product_above_ppl_limit(op_name):
    with pytest.raises(tvm.error.TVMError, match=r"requires h\*w <= 65535"):
        _emit_source_without_address_assignment(
            _make_exp_family_with_large_hw(op_name))


@pytest.mark.parametrize("reduce", (T.ppl_reduce_sum, T.ppl_reduce_max))
def test_reduction_rejects_unrepresentable_aligned_width(reduce):

    @T.prim_func
    def reduction():
        T.func_attr({"global_symbol": "reduction"})
        with T.Kernel(1, 1, is_cpu=True) as (_bx, _by):
            source = T.alloc_shared((1, 65535), "float16")
            destination = T.alloc_shared((1, 1), "float16")
            reduce(source, destination, dim=1)

    with pytest.raises(
            tvm.error.TVMError, match="aligned width 65536.*dim4 limit 65535"):
        tilelang.lower(reduction, target=_target(), runtime_mode="cmodel")
