# Copyright (c) Tile-AI Corporation.
# Licensed under the MIT License.
"""Compile-only checks for the TPUv7/PPL descriptor boundary.

These tests stop at source generation.  They do not load a CModel or dispatch
work to the PCIe device.
"""

import pytest

import tilelang
from tilelang import tvm
import tilelang.language as T
from tilelang.engine.phase import LowerAndLegalize, OptimizeForTarget
from tilelang.language.copy import buffer_to_tile_region


def _target(programming_model="tpukernel"):
    chip = "sg2260e" if programming_model == "rv" else "bm1690"
    return f"tpu -mcpu={chip} -tpu-programming-model={programming_model}"


def _make_local_copy(scope, width=32):

    @T.prim_func
    def local_copy(source: T.Tensor((1, width), "float32"), destination: T.Tensor((1, width),
                                                                                  "float32")):
        T.func_attr({"global_symbol": "local_copy", "tir.noalias": T.bool(True)})
        with T.Kernel(1, 1, is_cpu=True) as (_bx, _by):
            tile = T.alloc_shared((1, width), "float32", scope=scope)
            T.ppl_copy(source, tile)
            T.ppl_copy(tile, destination)

    return local_copy


def _make_raw_fill(scope, width):

    @T.prim_func
    def raw_fill():
        T.func_attr({"global_symbol": "raw_fill"})
        with T.Kernel(1, 1, is_cpu=True) as (_bx, _by):
            tile = T.alloc_shared((1, width), "float32", scope=scope)
            T.evaluate(
                T.call_extern("handle", "tl.tpu.fill", buffer_to_tile_region(tile, "w"),
                              T.float32(0)))

    return raw_fill


def _make_global_copy(width, dtype="uint8"):

    @T.prim_func
    def global_copy(source: T.Tensor((width,), dtype), destination: T.Tensor((width,), dtype)):
        T.func_attr({"global_symbol": "global_copy", "tir.noalias": T.bool(True)})
        with T.Kernel(1, 1, is_cpu=True) as (_bx, _by):
            T.ppl_copy(source, destination)

    return global_copy


def _make_exp_family_with_large_hw(op_name):

    @T.prim_func
    def exp_family():
        T.func_attr({"global_symbol": "exp_family"})
        with T.Kernel(1, 1, is_cpu=True) as (_bx, _by):
            # Each component is representable by dim4, while h*w is one past
            # the additional tpu_bdc_fp_exp limit.
            out = T.alloc_shared((1, 1, 256, 256), "float16")
            source = T.alloc_shared((1, 1, 256, 256), "float16")
            work0 = T.alloc_shared((1, 1, 256, 256), "float16")
            work1 = T.alloc_shared((1, 1, 256, 256), "float16")
            coeff = T.alloc_shared((64, 32), "float16")
            if op_name == "tl.tpu.exp":
                T.evaluate(
                    T.call_extern("handle", op_name, buffer_to_tile_region(out, "rw"),
                                  buffer_to_tile_region(work0, "rw"),
                                  buffer_to_tile_region(work1, "rw"),
                                  buffer_to_tile_region(coeff, "rw")))
            else:
                T.evaluate(
                    T.call_extern("handle", op_name, buffer_to_tile_region(out, "rw"),
                                  buffer_to_tile_region(source, "r"),
                                  buffer_to_tile_region(work0, "rw"),
                                  buffer_to_tile_region(work1, "rw"),
                                  buffer_to_tile_region(coeff, "rw")))

    return exp_family


def _emit_source_without_address_assignment(function):
    """Reach source codegen with synthetic addresses for a static guard test.

    Four 256x256 FP16 scratch tiles intentionally exceed physical LMEM.  The
    test is about the independent PPL exp descriptor rule, so it skips the
    allocator and gives every lowered Allocate a harmless compile-only address.
    Nothing generated by this helper is compiled, loaded, or dispatched.
    """
    target = tvm.target.Target(_target())
    global_symbol = str(function.attrs["global_symbol"])
    module = tvm.IRModule({global_symbol: function})
    module = LowerAndLegalize(module, target)
    module = OptimizeForTarget(module, target)

    for global_var, lowered in list(module.functions.items()):
        allocation_names = []

        def collect(node, allocation_names=allocation_names):
            if isinstance(node, tvm.tir.Allocate):
                allocation_names.append(node.buffer_var.name)

        tvm.tir.stmt_functor.post_order_visit(lowered.body, collect)
        for index, name in enumerate(allocation_names):
            lowered = lowered.with_attr("tilelang.tpu.lmem.address." + name,
                                        tvm.tir.IntImm("int64", index * 64))
        module.update_func(global_var, lowered)

    codegen = tvm._ffi.get_global_func("target.build.tilelang_tpu")
    return codegen(module, target)


@pytest.mark.parametrize("scope", ("shared", "shared.dyn", "local", "local.fragment"))
@pytest.mark.parametrize("programming_model", ("tpukernel", "rv"))
def test_all_normalized_local_scopes_reach_the_descriptor_paths(scope, programming_model):
    source = tilelang.lower(
        _make_local_copy(scope),
        target=_target(programming_model),
        runtime_mode="cmodel",
    ).kernel_source

    assert "__tilelang_tpu_tensor_info tile" in source
    expected = "rvt_dma_ld(" if programming_model == "rv" else "tpu_gdma_cpy_S2L("
    assert expected in source

    fill_source = tilelang.lower(
        _make_raw_fill(scope, 32),
        target=_target(programming_model),
        runtime_mode="cmodel",
    ).kernel_source
    assert "__tilelang_tpu_tensor_info tile" in fill_source


def test_non_descriptor_allocation_scope_fails_closed():
    with pytest.raises(tvm.error.TVMError, match="scope local.var"):
        tilelang.lower(
            _make_raw_fill("local.var", 32),
            target=_target(),
            runtime_mode="cmodel",
        )


def test_descriptor_dimension_limit_accepts_65535_and_rejects_65536():
    source = tilelang.lower(
        _make_global_copy(65535),
        target=_target(),
        runtime_mode="cmodel",
    ).kernel_source
    assert ".shape = {1, 1, 1, 65535}" in source

    with pytest.raises(tvm.error.TVMError, match="dimension 65536.*dim4 limit 65535"):
        tilelang.lower(
            _make_global_copy(65536),
            target=_target(),
            runtime_mode="cmodel",
        )

    with pytest.raises(tvm.error.TVMError, match="dimension 65536.*dim4 limit 65535"):
        tilelang.lower(
            _make_raw_fill("shared.dyn", 65536),
            target=_target(),
            runtime_mode="cmodel",
        )

    with pytest.raises(tvm.error.TVMError, match="expects a positive dimension"):
        tilelang.lower(
            _make_raw_fill("shared.dyn", 0),
            target=_target(),
            runtime_mode="cmodel",
        )


def test_local_rank_zero_descriptor_fails_closed():

    @T.prim_func
    def scalar_fill():
        T.func_attr({"global_symbol": "scalar_fill"})
        with T.Kernel(1, is_cpu=True) as _:
            scalar = T.alloc_shared((), "float32")
            T.evaluate(
                T.call_extern("handle", "tl.tpu.fill", buffer_to_tile_region(scalar, "w"),
                              T.float32(0)))

    with pytest.raises(ValueError, match="semantic-region-ABI.*rank 0.*rank 1 through 4"):
        tilelang.lower(
            scalar_fill,
            target=_target(),
            runtime_mode="cmodel",
        )


@pytest.mark.parametrize("dtype,dtype_name", [
    ("int8", "DT_INT8"),
    ("uint8", "DT_UINT8"),
    ("int16", "DT_INT16"),
    ("uint16", "DT_UINT16"),
    ("int32", "DT_INT32"),
    ("uint32", "DT_UINT32"),
])
def test_rv_integer_copy_descriptors_preserve_signedness(dtype, dtype_name):
    source = tilelang.lower(
        _make_global_copy(32, dtype),
        target=_target("rv"),
        runtime_mode="cmodel",
    ).kernel_source

    assert f"PRECISION({dtype_name}), SIGN({dtype_name})" in source
    assert f"PRECISION({dtype_name}), FP8TYPE({dtype_name})" not in source


@pytest.mark.parametrize("op_name", ("tl.tpu.exp", "tl.tpu.sigmoid"))
def test_exp_family_rejects_h_w_product_above_ppl_limit(op_name):
    with pytest.raises(tvm.error.TVMError, match=r"requires h\*w <= 65535"):
        _emit_source_without_address_assignment(_make_exp_family_with_large_hw(op_name))


@pytest.mark.parametrize("reduce", (T.ppl_reduce_sum, T.ppl_reduce_max))
def test_reduction_rejects_unrepresentable_aligned_width(reduce):

    @T.prim_func
    def reduction():
        T.func_attr({"global_symbol": "reduction"})
        with T.Kernel(1, 1, is_cpu=True) as (_bx, _by):
            source = T.alloc_shared((1, 65535), "float16")
            destination = T.alloc_shared((1, 1), "float16")
            reduce(source, destination, dim=1)

    with pytest.raises(tvm.error.TVMError, match="aligned width 65536.*dim4 limit 65535"):
        tilelang.lower(reduction, target=_target(), runtime_mode="cmodel")


@pytest.mark.parametrize("programming_model", ("tpukernel", "rv"))
def test_rank3_multichannel_full_copy_uses_one_lane_aware_descriptor(programming_model):

    @T.prim_func
    def rank3_copy(source: T.Tensor((1, 2, 32), "float32")):
        with T.Kernel(1, is_cpu=True) as _:
            tile = T.alloc_shared((1, 2, 32), "float32")
            T.ppl_copy(source, tile)

    source = tilelang.lower(
        rank3_copy,
        target=_target(programming_model),
        runtime_mode="cmodel",
    ).kernel_source

    assert ".shape = {1, 2, 1, 32}" in source
    if programming_model == "tpukernel":
        assert source.count("tpu_gdma_cpy_S2L(") == 1
    else:
        assert source.count("rvt_dma_ld(") == 1


def test_native_codegen_rejects_malformed_descriptor_operands():
    pointer_type = tvm.ir.PointerType(tvm.ir.PrimType("float32"), "shared")
    tile = tvm.tir.Var("tile", pointer_type)
    tile_buffer = tvm.tir.decl_buffer((8,),
                                      "float32",
                                      name="tile_buffer",
                                      data=tile,
                                      scope="shared")
    native_codegen = tvm._ffi.get_global_func("target.build.tilelang_tpu")

    def region(buffer, minimum=0, extent=8, access_mask=2):
        return tvm.tir.call_intrin("handle", tvm.tir.op.Op.get("tl.region"),
                                   tvm.tir.BufferLoad(buffer, [minimum]), access_mask, extent)

    def descriptor_function(operand):
        call = tvm.tir.call_extern("handle", "tl.tpu.fill", operand, tvm.tir.FloatImm("float32", 0))
        body = tvm.tir.Allocate(tile, "float32", [8], tvm.tir.IntImm("bool", 1),
                                tvm.tir.DeclBuffer(tile_buffer, tvm.tir.Evaluate(call)))
        return tvm.tir.PrimFunc(
            [],
            body,
        ).with_attr("global_symbol", "malformed_region").with_attr("tilelang.tpu.lmem.address.tile",
                                                                   tvm.tir.IntImm("int64", 0))

    malformed_cases = (
        (tvm.tir.IntImm("int32", 0), "whole-buffer tl.region operand"),
        (tvm.tir.call_intrin("handle", tvm.tir.op.Op.get("tl.region"), tvm.tir.IntImm("int32", 0),
                             2, 8), "must start with a BufferLoad marker"),
        (region(tile_buffer, minimum=1), "cover the whole Buffer from zero"),
        (region(tile_buffer, extent=7), "must cover the whole Buffer"),
        (region(tile_buffer, access_mask=1), "requires access mask 2"),
    )
    for operand, diagnostic in malformed_cases:
        with pytest.raises(tvm.error.TVMError, match=diagnostic):
            native_codegen(
                tvm.IRModule({"malformed_region": descriptor_function(operand)}),
                tvm.target.Target(_target()),
            )

    mismatched_view = tvm.tir.decl_buffer((4,),
                                          "float32",
                                          name="mismatched_view",
                                          data=tile,
                                          scope="shared")
    mismatched_function = descriptor_function(region(mismatched_view, extent=4))
    with pytest.raises(
            tvm.error.TVMError, match="logical Buffer shape disagrees with its descriptor owner"):
        native_codegen(
            tvm.IRModule({"mismatched_region": mismatched_function}),
            tvm.target.Target(_target()),
        )

    malformed_copy = tvm.tir.PrimFunc(
        [],
        tvm.tir.Evaluate(
            tvm.tir.call_extern("handle", "tl.tpu.copy", tvm.tir.IntImm("int32", 0),
                                tvm.tir.IntImm("int32", 0))),
    ).with_attr("global_symbol", "malformed_copy_region")
    with pytest.raises(tvm.error.TVMError, match="src must be a canonical tl.region descriptor"):
        native_codegen(
            tvm.IRModule({"malformed_copy_region": malformed_copy}),
            tvm.target.Target(_target()),
        )

    invalid_dtype_region = tvm.tir.call_intrin("int32", tvm.tir.op.Op.get("tl.region"),
                                               tvm.tir.BufferLoad(tile_buffer, [0]), 1, 8)
    invalid_dtype_copy = tvm.tir.call_extern("handle", "tl.tpu.copy", invalid_dtype_region,
                                             region(tile_buffer, access_mask=2))
    invalid_dtype_copy_body = tvm.tir.Allocate(
        tile, "float32", [8], tvm.tir.IntImm("bool", 1),
        tvm.tir.DeclBuffer(tile_buffer, tvm.tir.Evaluate(invalid_dtype_copy)))
    invalid_dtype_copy_function = tvm.tir.PrimFunc(
        [],
        invalid_dtype_copy_body,
    ).with_attr("global_symbol",
                "invalid_dtype_copy_region").with_attr("tilelang.tpu.lmem.address.tile",
                                                       tvm.tir.IntImm("int64", 0))
    with pytest.raises(tvm.error.TVMError, match="src tl.region must have handle dtype"):
        native_codegen(
            tvm.IRModule({
                "invalid_dtype_copy_region": invalid_dtype_copy_function,
            }),
            tvm.target.Target(_target()),
        )


def test_native_semantic_ops_validate_source_rank_and_full_shape():

    @T.prim_func
    def mismatched_rsqrt_shape():
        T.func_attr({"global_symbol": "mismatched_rsqrt_shape"})
        with T.Kernel(1, is_cpu=True) as _:
            dst = T.alloc_shared((2, 3, 1, 4), "float32")
            src = T.alloc_shared((1, 3, 2, 4), "float32")
            T.evaluate(
                T.call_extern("handle", "tl.tpu.rsqrt", buffer_to_tile_region(dst, "w"),
                              buffer_to_tile_region(src, "r")))

    with pytest.raises(ValueError, match="matching dst/src shapes"):
        tilelang.lower(
            mismatched_rsqrt_shape,
            target=_target(),
            runtime_mode="cmodel",
        )

    @T.prim_func
    def rank3_gemm():
        T.func_attr({"global_symbol": "rank3_gemm"})
        with T.Kernel(1, is_cpu=True) as _:
            lhs = T.alloc_shared((1, 16, 16), "float16")
            rhs = T.alloc_shared((1, 16, 16), "float16")
            out = T.alloc_shared((1, 16, 16), "float16")
            T.evaluate(
                T.call_extern("handle", "tl.tpu.gemm", buffer_to_tile_region(lhs, "r"),
                              buffer_to_tile_region(rhs, "r"), buffer_to_tile_region(out, "w"),
                              T.bool(False), T.bool(False), 16, 16, 16, T.bool(False)))

    with pytest.raises(ValueError, match="requires rank-2 A"):
        tilelang.lower(
            rank3_gemm,
            target=_target(),
            runtime_mode="cmodel",
        )


@pytest.mark.parametrize("programming_model", ("tpukernel", "rv"))
def test_native_gemm_rejects_output_storage_alias(programming_model):

    @T.prim_func
    def aliased_gemm():
        T.func_attr({"global_symbol": "aliased_gemm"})
        with T.Kernel(1, is_cpu=True) as _:
            lhs_and_out = T.alloc_shared((16, 16), "float16")
            rhs = T.alloc_shared((16, 16), "float16")
            T.evaluate(
                T.call_extern("handle", "tl.tpu.gemm", buffer_to_tile_region(lhs_and_out, "r"),
                              buffer_to_tile_region(rhs, "r"),
                              buffer_to_tile_region(lhs_and_out, "w"), T.bool(False), T.bool(False),
                              16, 16, 16, T.bool(False)))

    with pytest.raises(ValueError, match="output/accumulator C must use storage distinct"):
        tilelang.lower(
            aliased_gemm,
            target=_target(programming_model),
            runtime_mode="cmodel",
        )


def test_native_exp_rejects_transposed_coefficient_shape():

    @T.prim_func
    def malformed_exp_coefficients():
        T.func_attr({"global_symbol": "malformed_exp_coefficients"})
        with T.Kernel(1, is_cpu=True) as _:
            out = T.alloc_shared((4, 32), "float16")
            work0 = T.alloc_shared((4, 32), "float16")
            work1 = T.alloc_shared((4, 32), "float16")
            coeff = T.alloc_shared((32, 64), "float16")
            T.evaluate(
                T.call_extern("handle", "tl.tpu.exp", buffer_to_tile_region(out, "rw"),
                              buffer_to_tile_region(work0,
                                                    "rw"), buffer_to_tile_region(work1, "rw"),
                              buffer_to_tile_region(coeff, "rw")))

    with pytest.raises(ValueError, match="coefficient buffer must have shape"):
        tilelang.lower(
            malformed_exp_coefficients,
            target=_target(),
            runtime_mode="cmodel",
        )


@pytest.mark.parametrize("view_kind", ("elem_offset", "explicit_strides"))
def test_global_descriptor_rejects_unrepresented_buffer_views(view_kind):
    pointer_type = tvm.ir.PointerType(tvm.ir.PrimType("float32"), "global")
    data = tvm.tir.Var("data", pointer_type)
    kwargs = {"elem_offset": 1} if view_kind == "elem_offset" else {"strides": [1]}
    view = tvm.tir.decl_buffer((8,), "float32", name="view", data=data, scope="global", **kwargs)
    function = tvm.tir.PrimFunc(
        [data],
        tvm.tir.Evaluate(0),
        buffer_map={
            data: view
        },
    ).with_attr("global_symbol", "global_buffer_view")
    native_codegen = tvm._ffi.get_global_func("target.build.tilelang_tpu")

    with pytest.raises(
            tvm.error.TVMError, match="must be a canonical zero-offset contiguous Buffer"):
        native_codegen(
            tvm.IRModule({"global_buffer_view": function}),
            tvm.target.Target(_target()),
        )


def test_local_copy_rejects_nonzero_channel_minimum():
    global_pointer = tvm.ir.PointerType(tvm.ir.PrimType("float32"), "global")
    source_data = tvm.tir.Var("source", global_pointer)
    source = tvm.tir.decl_buffer((1, 2, 32),
                                 "float32",
                                 name="source",
                                 data=source_data,
                                 scope="global")
    local_pointer = tvm.ir.PointerType(tvm.ir.PrimType("float32"), "shared")
    tile_data = tvm.tir.Var("tile", local_pointer)
    tile = tvm.tir.decl_buffer((1, 2, 32), "float32", name="tile", data=tile_data, scope="shared")

    def region(buffer, indices, access_mask, extents):
        return tvm.tir.call_intrin("handle", tvm.tir.op.Op.get("tl.region"),
                                   tvm.tir.BufferLoad(buffer, indices), access_mask, *extents)

    copy = tvm.tir.call_extern("handle", "tl.tpu.copy", region(source, [0, 0, 0], 1, [1, 1, 32]),
                               region(tile, [0, 1, 0], 2, [1, 1, 32]))
    body = tvm.tir.Allocate(tile_data, "float32", [1, 2, 32], tvm.tir.IntImm("bool", 1),
                            tvm.tir.DeclBuffer(tile, tvm.tir.Evaluate(copy)))
    function = tvm.tir.PrimFunc(
        [source_data],
        body,
        buffer_map={
            source_data: source
        },
    ).with_attr("global_symbol", "local_channel_slice").with_attr("tilelang.tpu.lmem.address.tile",
                                                                  tvm.tir.IntImm("int64", 0))
    native_codegen = tvm._ffi.get_global_func("target.build.tilelang_tpu")

    with pytest.raises(tvm.error.TVMError, match="local C-axis minimum must be zero"):
        native_codegen(
            tvm.IRModule({"local_channel_slice": function}),
            tvm.target.Target(_target()),
        )


def test_global_descriptor_identity_does_not_depend_on_buffer_name():
    global_pointer = tvm.ir.PointerType(tvm.ir.PrimType("float32"), "global")
    source_data = tvm.tir.Var("source_data", global_pointer)
    unused_data = tvm.tir.Var("unused_data", global_pointer)
    source = tvm.tir.decl_buffer((4,),
                                 "float32",
                                 name="duplicate",
                                 data=source_data,
                                 scope="global")
    unused = tvm.tir.decl_buffer((8,),
                                 "float32",
                                 name="duplicate",
                                 data=unused_data,
                                 scope="global")

    local_pointer = tvm.ir.PointerType(tvm.ir.PrimType("float32"), "shared")
    tile_data = tvm.tir.Var("tile", local_pointer)
    tile = tvm.tir.decl_buffer((4,), "float32", name="tile_buffer", data=tile_data, scope="shared")

    def region(buffer, access_mask, extent):
        return tvm.tir.call_intrin("handle", tvm.tir.op.Op.get("tl.region"),
                                   tvm.tir.BufferLoad(buffer, [0]), access_mask, extent)

    copy = tvm.tir.call_extern("handle", "tl.tpu.copy", region(source, 1, 4), region(tile, 2, 4))
    body = tvm.tir.Allocate(tile_data, "float32", [4], tvm.tir.IntImm("bool", 1),
                            tvm.tir.DeclBuffer(tile, tvm.tir.Evaluate(copy)))
    function = tvm.tir.PrimFunc(
        [source_data, unused_data],
        body,
        buffer_map={
            source_data: source,
            unused_data: unused
        },
    ).with_attr("global_symbol",
                "duplicate_buffer_names").with_attr("tilelang.tpu.lmem.address.tile",
                                                    tvm.tir.IntImm("int64", 0))

    source_code = tvm._ffi.get_global_func("target.build.tilelang_tpu")(
        tvm.IRModule({"duplicate_buffer_names": function}),
        tvm.target.Target(_target()),
    )

    assert "v3 = {.shape = {1, 1, 1, 4}" in source_code
    assert "v4 = {.shape = {1, 1, 1, 8}" in source_code
    assert ".addr = v3.addr +" in source_code
